services:
  photos:
    image: flowlogix/mirror-immich
    container_name: photos
    ports:
      - "9090:8080"
    env_file:
      - path: defaults.env
        required: true
      - path: .env
        required: false
    environment:
      - HOST_USER_HOME=${HOME}
      - localtime_path=/home/flowlogix/var/host-etc/localtime
    volumes:
      - ${HOME}/Pictures:${HOME}/Pictures
      - /etc:/home/flowlogix/var/host-etc:ro
    restart: unless-stopped